# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-07-12 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20200708_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arnurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url]),
        ),
    ]
